### ISSUE TITLE
Error: "length(model_encoding[[2]]) == max(round(tmp_bm[[1]])) is not TRUE"

### ISSUE THREAD

**Issue by ShuonanChen** [cheeyeelim/BTR#1]
Hi, 

The method is interesting! But I am getting an error when I fit the model without initialization of the network: 

```
edata_ESC <- initialise_data(data_ESC)
final_model = model_train(cdata = edata_ESC, max_varperrule = 100, verbose = T)
```

Gives me: 

```
Preparing data for analysis.
Start training.
Current iteration: 1.
Stage 1: Exploring neighbouring models.
Error in { : 
  task 1 failed - "length(model_encoding[[2]]) == max(round(tmp_bm[[1]])) is not TRUE"
In addition: Warning messages:
1: In rle(round(act_vec))$lengths + rle(round(inh_vec))$lengths :
  longer object length is not a multiple of shorter object length
2: In rle(round(act_vec))$lengths + rle(round(inh_vec))$lengths :
  longer object length is not a multiple of shorter object length
```

I am not totally sure what the argument `max_varperrule` is doing. 
Therefore I also tried:

```
final_model = model_train(cdata = edata_ESC, verbose = T)
```
and then it gives:
```
Preparing data for analysis.
Start training.
Current iteration: 1.
Stage 1: Exploring neighbouring models.
Error in { : 
  task 1 failed - "length(comb_rule) == length(gene_var) is not TRUE"
In addition: Warning message:
In rle(round(act_vec))$lengths + rle(round(inh_vec))$lengths :
  longer object length is not a multiple of shorter object length
```

Btw, I have 96 genes.
```
dim(edata_ESC)
[1] 89 96
```

Any thoughts? Am I missing something? Thank you very much!

**Comment by ShuonanChen** [comment]
Update:
When I subset my data frame so that n>>p (e.g., n = 89, p = 10), it worked. But not when n = 89, p = 86. Is there a constrain on the data that I should have been aware of? Thank you !

**Comment by cheeyeelim** [comment]
Hi, thanks for trying out the algorithm.

The largest limitation of the algorithm is the combinatorial explosion in trying different combinations of Boolean logic among the genes. So the maximum number of genes that can be used in the algorithm is around 20 genes. However, as you have noticed, the algorithm will work best with 10-15 genes. Note that this also depends on how big your dataset is (i.e. n).

The errors you encountered are likely due to out of memory issue,  resulting in some of the R processes being killed by your operating system.
